build:
    environment:
        php:
            version: 7.1, 7.2
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=build/logs/clover.xml'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'
filter:
    excluded_paths:
        - tests/*
